const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const fs=require('node:fs/promises');const assert=require('node:assert/strict');
async function main(){const base='http://127.0.0.1:8087',out='tests/prd-v2-browser-2026-10-05';const result={actual_browser:true,actual_api:true,checks:{}};const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE});const page=await browser.newPage();try{
 await page.goto(base);await page.locator('#recommendation').filter({hasText:'제안'}).waitFor();const recommendation=await(await page.request.get(base+'/api/training/recommendation')).json();result.recommendation_id=recommendation.recommendation_id;
 await page.locator('#request-data').selectOption('existing');const start=page.waitForResponse(r=>r.url().endsWith('/api/training/requests')&&r.request().method()==='POST');await page.locator('#start-recommendation').click();const started=await(await start).json();result.request_id=started.request_id;
 const poll=async()=>{let value;const deadline=Date.now()+140000;do{value=await(await page.request.get(base+'/api/training/requests/'+started.request_id)).json();if(['ready','failed','needs_clarification'].includes(value.status))break;await page.waitForTimeout(500);}while(Date.now()<deadline);return value;};
 let request=await poll();result.initial_status=request.status;
 if(request.status==='needs_clarification'){await page.locator('#clarification-message').fill('추천한 난이도와 과제 유형을 그대로 유지합니다. 신규 유저 D1~D7 미재접속·D8 관측 완료·플랫폼별 비교를 대상으로 진행해주세요.');const clarification=page.waitForResponse(r=>r.url().endsWith('/clarify')&&r.request().method()==='POST');await page.locator('#send-clarification').click();await clarification;request=await poll();result.clarification_answer=true;}
 assert.equal(request.status,'ready',request.error);await page.waitForURL('**/?attempt='+request.attempt_id);await page.locator('#workspace').waitFor();const attempt=await(await page.request.get(base+'/api/attempts/'+request.attempt_id)).json();assert.equal(attempt.difficulty,recommendation.difficulty);assert.equal(attempt.task_kind,recommendation.task_kind);result.attempt_id=request.attempt_id;result.status='passed';result.actual_kind=attempt.task_kind;result.actual_difficulty=attempt.difficulty;
 await page.screenshot({path:out+'/recommendation.png',fullPage:true});
}catch(e){result.status='failed';result.error=e.message;}finally{await fs.writeFile(out+'/recommendation.json',JSON.stringify(result,null,2));await browser.close();}console.log(JSON.stringify(result));}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
