const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs/promises');const path=require('node:path');const assert=require('node:assert/strict');
const base=process.env.VERIFY_BASE_URL || 'http://127.0.0.1:8087';
const result={actual_browser:true,actual_api:true,actual_model:true,actual_db:true,model_call_budget:8,model_actions_started:0,checks:{},flows:[],console_errors:[],cleanup:[]};
async function main(){
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE || undefined});const context=await browser.newContext({viewport:{width:1280,height:900}});const page=await context.newPage();page.on('pageerror',e=>result.console_errors.push(e.message));page.on('dialog',d=>d.type()==='beforeunload'?d.accept():d.dismiss());let deletes=0;page.on('request',r=>{if(r.method()==='DELETE')deletes++;});
 const owned=[]; const record=async(name,fn)=>{try{result.checks[name]=await fn();}catch(e){result.checks[name]={passed:false,error:e.message};}};
 const loadHome=async()=>{await page.goto(base);await page.locator('#recommendation').filter({hasText:'제안'}).waitFor({timeout:20000});};
 const beginRequest=async(message,level,kind)=>{if(result.model_actions_started>=8)throw new Error('Model action budget exhausted');await loadHome();await page.locator('#training-request').fill(message);await page.locator('#request-level').selectOption(level);await page.locator('#request-kind').selectOption(kind);await page.locator('#request-data').selectOption('existing');result.model_actions_started++;const responsePromise=page.waitForResponse(r=>r.url()===base+'/api/training/requests' && r.request().method()==='POST');await page.locator('#request-training').click();const response=await responsePromise;const data=await response.json();if(!response.ok())throw new Error(JSON.stringify(data));let rid=data.request_id;const deadline=Date.now()+100000;let status;do{status=await(await context.request.get(base+'/api/training/requests/'+rid)).json();if(['ready','failed','needs_clarification','cancelled','interrupted','unsupported'].includes(status.status))break;await page.waitForTimeout(500);}while(Date.now()<deadline);return status;};
 try{
 await loadHome();const initialIds=new Set((await(await context.request.get(base+'/api/attempts')).json()).attempts.map(a=>a.attempt_id));
 await record('keyboard_delete_cancel',async()=>{const count=await page.locator('#attempts article').count();const button=page.locator('#attempts article').first().getByRole('button',{name:'훈련 삭제',exact:true});await button.focus();await page.keyboard.press('Enter');await page.getByRole('dialog').waitFor();assert.equal(await page.getByRole('button',{name:'삭제 취소',exact:true}).evaluate(n=>document.activeElement===n),true);await page.keyboard.press('Tab');await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);assert.equal(await page.locator('#attempts article').count(),count);assert.equal(deletes,0);return {passed:true,delete_requests:deletes,list_count:count};});
 await record('home_390',async()=>{await page.setViewportSize({width:390,height:844});const width=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));assert.ok(width.scrollWidth<=width.width);return {passed:true,...width};});
 await record('recommendation_change',async()=>{await page.locator('#change-recommendation').click();await page.locator('#notice').filter({hasText:'바꾸고'}).waitFor();await page.locator('#request-level').selectOption('advanced');assert.equal(await page.locator('#request-level').inputValue(),'advanced');return {passed:true,selected:'advanced',model_call:false};});
 await record('unsupported_input_preserved',async()=>{const message='매출 결제와 전투 경제 데이터로 분석 문제를 만들어줘';const status=await beginRequest(message,'auto','auto');assert.ok(['failed','needs_clarification','unsupported'].includes(status.status));assert.equal(await page.locator('#training-request').inputValue(),message);return {passed:true,status:status.status,error_code:status.error_code,reason:status.error};});
 await record('clarification_explicit_conflict',async()=>{const message='고급 업무 요청 구체화 문제를 원합니다. D1~D7 미재접속 설계입니다.';const status=await beginRequest(message,'beginner','calculation');const preserved=await page.locator('#training-request').inputValue()===message;assert.ok(preserved);return {passed:status.status==='needs_clarification',status:status.status,questions:status.questions,error_code:status.error_code,input_preserved:preserved};});
 for(const kind of ['calculation','review','investigation']){
 const flow={kind};result.flows.push(flow);
 try{
 const message={calculation:'접속 데이터로 초급 D1~D7 기간 미재접속 지표 계산 문제를 내줘.',review:'접속 데이터로 초급 D1~D7 미재접속 집계 오류 수정 검토 문제를 내줘.',investigation:'접속 데이터로 초급 집단과 기간의 D1~D7 미재접속 현상 조사 문제를 내줘.'}[kind];
 const status=await beginRequest(message,'beginner',kind);flow.request_status=status.status;flow.request_error=status.error_code;flow.questions=status.questions;
 if(status.status!=='ready')continue;const id=status.attempt_id;if(initialIds.has(id))throw new Error('Refusing to mutate preexisting attempt');owned.push(id);flow.attempt_id=id;await page.waitForURL('**/?attempt='+id,{timeout:20000});await page.locator('#workspace').waitFor();flow.explicit_type=await(await context.request.get(base+'/api/attempts/'+id)).json();flow.explicit_type={kind:flow.explicit_type.task_kind,difficulty:flow.explicit_type.difficulty};assert.equal(flow.explicit_type.kind,kind);assert.equal(flow.explicit_type.difficulty,'beginner');
 await page.setViewportSize({width:390,height:844});const width=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));flow.analysis_390={passed:width.scrollWidth<=width.width,...width};
 await page.locator('#sql').fill('SELECT count(*) AS users FROM users');await page.locator('#execute').click();await page.locator('#executions').filter({hasText:'状態'.replace('状態','상태: success')}).waitFor({timeout:20000});flow.sql_success=true;await page.getByRole('button',{name:'기록에 저장',exact:true}).first().click();await page.getByRole('button',{name:'저장 완료',exact:true}).waitFor({timeout:20000});flow.saved=true;
 await page.locator('[data-section="problem_definition"]').fill('가입 기간 신규 고유 유저를 대상으로 D1 00:00부터 D8 00:00 전까지 미재접속을 정의하고 D8까지 관측 완료한 유저만 포함한다.');await page.locator('[data-section="hypothesis"]').fill('세션 JOIN 행 수와 고유 유저 수를 구분하고 대상 기간·관측 완료를 먼저 확인한다. 집단 차이는 원인의 증명이 아니다.');await page.locator('button[data-tab="report"]').click();await page.locator('#discoveries').fill('전체 users 표의 유저 수 200명을 실제 SQL로 확인했다. 코호트·관측·기간 내 재접속 조건을 적용한 미재접속 결과는 아직 계산하지 않아 미확인이다.');const evidence=page.locator('#claims input[type=checkbox]').first();await evidence.check();await page.locator('[data-section="limitations"]').fill('전체 유저 수를 미재접속 지표로 대체할 수 없다. 관측 자료만으로 원인을 단정하지 않는다.');await page.locator('[data-section="next_actions"]').fill('같은 가입 기간·관측 조건으로 고유 유저별 미재접속을 계산하고 집단별 표본 수와 차이를 확인한다.');await page.locator('#submit-report').click();await page.locator('#reports').filter({hasText:'보고서 v1'}).waitFor({timeout:20000});flow.report_submitted=true;
 if(result.model_actions_started<8){result.model_actions_started++;const reviewResponse=page.waitForResponse(r=>r.url().includes('/reports/') && r.url().endsWith('/review') && r.request().method()==='POST',{timeout:110000});await page.getByRole('button',{name:'이 제출본 리뷰 요청',exact:true}).first().click();const review=await(await reviewResponse).json();flow.review_status=review.status;flow.review_error=review.error?.code || null;}
 await page.locator('button[data-tab="analysis"]').click();await page.locator('#sql').fill('');await page.reload();await page.locator('#workspace').waitFor({timeout:20000});await page.locator('#saved').filter({hasText:'저장 근거 1'}).waitFor({state:'attached',timeout:20000});flow.resume_saved=true;const reopened=await(await context.request.get(base+'/api/attempts/'+id)).json();flow.resume_report=reopened.reports.length===1;flow.resume_reviews=reopened.reviews.length;
 }catch(e){flow.error=e.message;}
 }
 result.checks.console_clean={passed:result.console_errors.length===0};
 }finally{
 for(const id of owned){try{const response=await context.request.delete(base+'/api/attempts/'+id,{data:{}});result.cleanup.push({attempt_id:id,status:response.status(),deleted:response.ok()});}catch(e){result.cleanup.push({attempt_id:id,deleted:false,error:e.message});}}
 result.finished_at=new Date().toISOString();await fs.writeFile(path.resolve('tests/artifacts/verification-v2-extended-browser-2026-10-04.json'),JSON.stringify(result,null,2));await browser.close();
 }
 console.log(JSON.stringify(result));
}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
